routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('locale/{locale}',function ($locale) {
   Session::put('locale',$locale);
   return redirect()->back();
});


Route::get('/home', 'HomeController@index')->name('home');

Route::any('/search','ThreadController@search');
Route::get('threads/create', 'ThreadController@create');
Route::get('threads', 'ThreadController@index');
Route::get('threads/{category}/{thread}', 'ThreadController@show');
Route::get('threads/{category}','ThreadController@index');
Route::get('/profiles/show/{user}', 'ProfileController@show')->name('profile');
Auth::routes(['verify'=>true]);
Route::get('/notifications', 'ProfileController@notifications');
Route::post('/profiles/show/{user}/follow', 'ProfileController@follow')->name('user.follow');
Route::post('/profiles/show/{user}/unfollow', 'ProfileController@unfollow')->name('user.unfollow');
Route::get('edit/threads/{category}/{thread}', 'ThreadController@edit');
Route::patch('edit/threads/{category}/{thread}', 'ThreadController@update');
Route::delete('threads/{category}/{thread}', 'ThreadController@destroy');
Route::delete('/replies/{reply}', 'ReplyController@destroy');
Route::get('threads/{category}/{thread}/replies/{reply}/edit', 'ReplyController@edit');
Route::patch('threads/{category}/{thread}/replies/{reply}/edit', 'ReplyController@update');
Route::post('/replies/{reply}/favorites', 'FavoriteController@store');
Route::post('threads', 'ThreadController@store');
Route::post('/threads/{category}/{thread}/replies', 'ReplyController@store');
Route::get('/profiles/edit', 'ProfileController@edit');
Route::patch('/profiles/edit', 'ProfileController@update');
Route::post('/threads/{category}/{thread}/subscriptions', 'ThreadSubscriptionController@store')->middleware('auth');
Route::delete('/threads/{category}/{thread}/subscriptions', 'ThreadSubscriptionController@destroy')->middleware('auth');


Route::group(['middleware'=>'admin'],function() {

    Route::get('/manage/users', 'ManageUsersController@showUserList')->name('Manage users');
    Route::post('/manage/users/delete/{id}', 'ManageUsersController@deleteUser')->name('Delete user');
    Route::patch('/manage/users/role', 'ManageUsersController@updateUserRole')->name('Change user access');
    Route::get('/manage/users/showByRoles/{roles}', 'ManageUsersController@showUsersByRoles')->name('Show users by role');
    Route::get('/manage/categories', 'ManageCategoriesController@showCategoryForm')->name('Manage categories');
    Route::post('/manage/categories/add', 'ManageCategoriesController@addCategory')->name('Add category');
    Route::post('/manage/categories/delete', 'ManageCategoriesController@deleteCategory')->name('Delete category');


});

app/Favorited.php
<?php


namespace App;
use Illuminate\Database\Eloquent\Model;

trait Favorited
{

    protected static function bootFavoritable()
    {
        static::deleting(function ($model) {
            $model->favorites->each->delete();
        });
    }


    public function favorites()
    {
        return $this->morphMany('App\Favorite', 'favorited');
    }


    public function favorite()
    {
        $attributes=['user_id'=>auth()->id()];
        if(! $this->favorites()->where($attributes)->exists())
        {
            return $this->favorites()->create($attributes);
        }
    }

    public function unfavorite()
    {
        $attributes = ['user_id' => auth()->id()];
        $this->favorites()->where($attributes)->get()->each->delete();
    }

    public function isFavorited()
    {
        return ! ! $this->favorites()->where('user_id',auth()->id())->count();
    }

    public function getFavoritesCountAttribute()
    {
        return $this->favorites()->count();
    }

}

app/Thread.php
<?php

namespace App;

use App\Notifications\ThreadWasUpdated;
use Illuminate\Database\Eloquent\Model;
use App\Filters\ThreadsFilter;
use Illuminate\Database\Eloquent\Builder;

class Thread extends Model
{


    protected $fillable = ['title','body','category_id','user_id','slug'];
    protected $appends = ['isSubscribedTo'];

    protected static function boot()
    {
        parent::boot();
        static::addGlobalScope('replyCounter',function($builder)
        {
            $builder->withCount('replies');
        });
        static::deleting(function ($thread){
            $thread->replies->each->delete();
        });

    }
    public function path()
    {
        return "/threads/{$this->category->slug}/{$this->slug}";
    }

    public function category()
    {
        return $this->belongsTo('App\Category','category_id');
    }

    public function replies()
    {
        return $this->hasMany('App\Reply');
    }

    public function user()
    {
        return $this->belongsTo('App\User','user_id');
    }

    public function addReply($replyRequest)
    {
        $reply = $this->replies()->create($replyRequest);

        $this->subscriptions
            ->filter(function ($sub) use ($reply) {
                return $sub->user_id != $reply->user_id;
            })
            ->each->notify($reply);
        return $reply;
    }

    public function scopeFilter($query, ThreadsFilter $filters)
    {
        return $filters->apply($query);
    }


    public function subscribe($userId = null)
    {
        $this->subscriptions()->create([
            'user_id' => $userId ?: auth()->id()
        ]);

        return $this;

    }

    public function unsubscribe($userId = null)
    {
        $this->subscriptions()
            ->where('user_id', $userId ?: auth()->id())
            ->delete();
    }

    public function subscriptions()
    {
        return $this->hasMany('App\ThreadSubscription');
    }

    public function getIsSubscribedToAttribute()
    {
        return $this->subscriptions()
            ->where('user_id', auth()->id())
            ->exists();
    }

    public function isSubscribed()
    {
        return !! $this->subscriptions()->where('user_id',auth()->id())->count();
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }



}

app/Http/Controllers/ThreadController.php
<?php

namespace App\Http\Controllers;

use Artesaos\SEOTools\Facades\SEOMeta;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use App\Thread;
use App\Category;
use App\Filters\ThreadsFilter;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Str;
use Illuminate\View\View;

class ThreadController extends Controller
{
    //

   public function __construct()
   {
       $this->middleware('auth') ->except(['index','show']);
   }

    public function index(Category $category, ThreadsFilter $filters)
  {

      SEOMeta::setTitle('Threads');
        $threads = $this->getThreads($category,$filters);

      return view('threads.index', compact('threads'));
  }

    /**
     * @param Thread $thread
     * @param integer $category
     * @return Factory|View
     */

  public function show($category, Thread $thread)
  {
      SEOMeta::setTitle($thread->title);
      return view('threads.show',[
          'thread' =>$thread,
          'replies' =>$thread->replies()->paginate(10)
      ]);
  }

  public function store (Request $request)
  {
      $this->validate($request, [
          'title' =>'required|unique:threads',
          'body' => 'required|max:1000',
          'category_id' => 'required'
      ]);



      $slug = Str::slug(request('title'));

      $thread = Thread::create([
          'user_id' => auth()->id(),
          'category_id' => request('category_id'),
          'title' => request('title'),
          'body' => request('body'),
          'slug'=> $slug,
      ]);


      return redirect($thread->path())->with('success',trans('messages.success_create_thread'));
  }

  protected function getThreads(Category $category, ThreadsFilter $filters)
  {
      $threads = Thread::latest()->filter($filters);

      if ($category->exists)
      {
          $threads->where('category_id',$category->id);
      }

      return $threads->get();
  }

  public function create()
  {
      SEOMeta::setTitle('Create thread');
      return view('threads.create');
  }

  public function destroy ($category, Thread $thread)
  {
      $this->authorize('delete', $thread);
      $thread->delete();
      return redirect('/threads')->with('error', trans('messages.error_delete_thread'));
  }

    public function edit(Category $category, Thread $thread)
    {

        return view('threads.edit',compact('thread'));
    }


    public function update(Request $request, Category $category, Thread $thread)
    {

        $this->validate($request, [
            'body' => 'required|max:1000',
            'category_id' => 'required',
        ]);


     $thread->body = $request->body;
     $thread->category_id = $request->category_id;

        $thread->save();

        $input = $request->only('body','category_id');
        $thread->update($input);


        return redirect('/')->with('success', trans('messages.success_update_thread'));

    }


    public function search()
    {
        $q = Input::get('q');
        if ($q != "") {
            $thread = Thread::where('title', 'LIKE', '%' . $q . '%')->get();
            if (count($thread) > 0)
                return view('search')->withDetails($thread)->withQuery($q);

        } else return view('search')->with('error', 'No threads found. Try to search again!');


        return redirect()->back()->with('error', 'No threads found. Try to search again!');
        }
}

resources/views/threads/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">@lang('threads_create.create')</div>

                    <div class="panel-body">
                        <form method="POST" action="/threads">
                            {{ csrf_field() }}


                            <div class="form-group">
                                <label for="title">@lang('threads_create.title')</label>
                                <input type="text" class="form-control" id="title" name="title"
                                       value="{{ old('title') }}" required>
                            </div>

                            <div class="form-group">
                                <label for="body">@lang('threads_create.body')</label>
                                <textarea name="body" id="body" class="form-control"
                                          rows="8" required>{{ old('body') }}</textarea>
                            </div>


                            <div class="form-group">
                                <label for="category_id">@lang('threads_create.choose')</label>
                                <select name="category_id" id="category_id" class="form-control" required>
                                    <option value="">@lang('threads_create.choose_one')</option>

                                    @foreach ($categories as $category)
                                        <option value="{{ $category->id }}" {{ old('category_id') == $category->id ? 'selected' : '' }}>
                                            {{ $category->name }}
                                        </option>
                                    @endforeach
                                </select>
                            </div>


                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">@lang('threads_create.publish')</button>
                            </div>

                            @if (count($errors))
                                <ul class="alert alert-danger">
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            @endif
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/threads/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Update thread</div>

                    <div class="panel-body">
                            <form action="/edit/threads/{{$thread->category->slug}}/{{$thread->slug}}" method="POST">

                            {{ csrf_field() }}
                                {{ method_field('PATCH') }}
                                <div class="form-group {{ $errors->has('body') ? ' has-error' : '' }}">
                                    <label for="body" class="control-label"><b>@lang('threads_create.body')</b></label>
                                    <textarea name="body" id="body" class="form-control"
                                              rows="8" required> {{$thread->body}}</textarea>

                                    @if ($errors->has('body'))
                                        <span class="help-block">
                                     <strong>{{$errors->first('body')}}</strong>
                                        </span>
                                    @endif
                                </div>

                                <div class="form-group">
                                    <label for="category_id">@lang('threads_create.choose')</label>
                                    <select name="category_id" id="category_id" class="form-control" required>
                                        <option value="">@lang('threads_create.choose_one')</option>

                                        @foreach ($categories as $category)
                                            <option value="{{ $category->id }}" {{ old('category_id') == $category->id ? 'selected' : '' }}>
                                                {{ $category->name }}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>


                                <div class="form-group">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>

                            @if (count($errors))
                                <ul class="alert alert-danger">
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            @endif
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/threads/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
        <div class=" panel panel-default">


            <form action="/search" method="POST" role="search">
                {{ csrf_field() }}
                <div class="input-group">
                    <input type="text" class="form-control" name="q"
                           placeholder="Search threads"> <span class="input-group-btn">
            <button type="submit" class="btn btn-default">
                <span class="fa fa-search"></span>
            </button>
        </span>
                </div>
            </form>


            <div class = "panel-heading"> @lang('threads_index.list_of_threads')

            </div>


                @foreach($threads as $thread)
                    <div> <a href="{{$thread->path()}}">{{$thread->title}} ({{ $thread->replies_count }})</a> </div>

            @endforeach


        </div>
</div>
    </div>
</div>
@endsection

resources/views/threads/show.blade.php
@extends('layouts.app')

@section('content')
    <h2 class="text-center">{{$thread->title}}</h2>

    <div class="card mb-3">

        <div class="container-fluid">
            <div class="row">
                <div class="col-md-3 bg-light">
                    <p class="text-center mt-2">
                        <img src="/storage/avatars/{{ $thread->user->avatar_name }}"  class="rounded-circle" width="150" height="150"/>
                    </p>
                    <p class="text-center font-weight-bold">
                        <a href="{{ route('profile', $thread->user) }}">{{ $thread->user->name }}</a>
                    </p>
                    <p>
                        @lang('threads_show.number_of_replies') {{ $thread->replies_count }}
                    </p>

                    <form method="POST" action="/threads/{{$thread->category->slug}}}/{{$thread->slug}}/subscriptions">
                        {{ csrf_field() }}

                        <button type="submit" class="btn btn-warning" {{ $thread->isSubscribed() ? 'disabled' : '' }}>
                            @lang('threads_show.subscribe')
                        </button>

                    </form>

                    @can ('delete',$thread)
                        <form action="{{ $thread->path() }}" method="POST">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}

                            <button type="submit" class="btn btn-danger">@lang('threads_show.delete_thread')</button>
                        </form>
                    @endcan

                    @can ('update',$thread)

                        <div><a href="/edit/threads/{{$thread->category->slug}}/{{$thread->slug}} "
                                class="btn btn-primary">@lang('threads_show.edit_button')</a></div>

                    @endcan

                </div>
                <div class="col-md-9">
                    <p class="font-weight-bold">{{$thread->title}}, {{$thread->category->name}} </p>
                    <p class="mt-1">
                        <small> {{$thread->created_at}}</small>
                    </p>

                    <hr>
                    <p>
                        {{$thread->body}}
                    </p>

                    <hr>
                    <p class="font-italic">
                        @lang('threads_show.updated_at') {{$thread->updated_at}}
                    </p>


                </div>
            </div>
        </div>

    </div>

    @foreach($replies as $reply)
        <div class="card mb-3">

            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-3 bg-light">
                        <p class="text-center mt-2">
                            <img src="/storage/avatars/{{ $reply->user->avatar_name }}" class="rounded-circle" width="150" height="150"/>
                        </p>
                        <p class="text-center font-weight-bold">
                            <a href="{{ route('profile', $reply->user) }}">{{ $reply->user->name }}</a>
                        </p>
                        <p>
                        <form method="POST" action="/replies/{{ $reply->id }}/favorites">
                            {{ csrf_field() }}

                            <button type="submit" class="btn btn-info" {{ $reply->isFavorited() ? 'disabled' : '' }}>
                                @lang('threads_show.favorite')
                                {{ $reply->favorites_count }}
                            </button>
                        </form>
                        </p>

                        @can ('delete', $reply)
                            <div class="panel-footer">
                                <form method="POST" action="/replies/{{ $reply->id }}">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}

                                    <button type="submit"
                                            class="btn btn-danger btn-xs">@lang('threads_show.delete')</button>

                                    @can ('update',$reply)
                                        <div>
                                            <a href="/threads/{{$thread->category->slug}}/{{$thread->slug}}/replies/{{$reply->id}}/edit"
                                               class="btn btn-primary">@lang('threads_show.edit_button')</a></div>
                                    @endcan
                                </form>
                            </div>
                        @endcan

                    </div>
                    <div class="col-md-9">
                        <p class="font-weight-bold">{{$thread->title}}, {{$thread->category->name}} </p>
                        <p class="mt-1">
                            <small> {{$reply->created_at}}</small>
                        </p>

                        <hr>
                        <p>
                            {{$reply->body}}
                        </p>

                        <hr>
                        <p class="font-italic">
                            @lang('threads_show.updated_at') {{$reply->updated_at}}
                        </p>


                    </div>
                </div>
            </div>
            {{ $replies->links() }}
            @endforeach
        </div>


        @if (Auth::check())
            <div class="col-md-8">
                <form method="POST" action="{{ $thread->path() . '/replies' }}">
                    {{ csrf_field() }}

                    <div class="form-group">
                        <textarea name="body" id="body" class="form-control"
                                  placeholder=@lang('threads_show.reply') rows="5"></textarea>
                    </div>

                    <button type="submit" class="btn btn-success">@lang('threads_show.post')</button>

                    @if (count($errors))
                        <ul class="alert alert-danger">
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    @endif
                </form>
                <div>

                </div>
            </div>

        @else
            <p class="text-center">@lang('threads_show.please')
                <a href="{{ route('login') }}">@lang('threads_show.sign_in')</a>@lang('threads_show.participate')
            </p>
        @endif


@endsection